spring:
  application:
    name: Library API
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver # Class of connection
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # none, create, create-drop